### ISSUE TITLE
Download part of the video to stream from certain time

### ISSUE THREAD

**Issue by bcashier** [a1phat0ny/torrodle#2]
Hi,

Is there a wa to stream a video starting from for a example 30min while this part not yet downloaded?

When we select a certain duration, this part will start automatically to be downloaded.

Thank you

**Comment by a1phat0ny** [comment]
Yes, it is possible. Since `torrodle` uses http localhost to serve the video file, you should be able to jump to a certain timestamp and `torrodle` will start downloading that particular part automatically.
